name: CI/CD for Dockerized Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            # 1st step: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v2

            # 2nd step: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            # 3rd step: Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            # 4th step: Run tests
            - name: Run tests
              run: pytest
    
    build-and-publish:
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
            # 1st step: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v2

            # 2nd step: setup Docker buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            # 3rd step: Build and push Docker image 
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
            
            - name: Image digest
              run: echo ${{ steps.build-and-publish.outputs.digest }}